### PR TITLE
Promise.defer() replaced by new Promise(function(resolve, reject)

### PR DESCRIPTION
**Pull request by Nishchit14**
For this issue #48 

Promise.defer() is not part of the Promise API anymore:

https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred

```javascript
var deferred = Promise.defer();
doSomething(function cb(err, res) {
    if (err) deferred.reject(err); else deferred.resolve(res);
});
return deferred.promise;
```

is now replaced to 

```javascript
return new Promise(function(resolve, reject) {
    doSomething(function cb(err, res) {
        if (err) reject(err); else resolve(res);
    });
});
```

### CODE REVIEW

**Comment by mheiber** [comment]
Thanks for the great library. Hope you can merge this pull request soon - the warnings about `Promise.defer` are clogging up the console.

**Comment by yanyiluo** [comment]
+1 to this change!

**Comment by bbackbum** [comment]
+1 more. Please this pull request soon. i can't your greate library now. i hope use as soon as library!

**Comment by bbackbum** [comment]
i hope this change angain !!!

**Comment by Nishchit14** [comment]
@adelimon @adrianblynch @Timespace7 @guyonroche

Who are the maintainer ? 
Please do followup , people are taking interest in this libs.

**Comment by bbackbum** [comment]
is he "guyonroche" maintainer ??

**Comment by yanyiluo** [comment]
let's cool down on the comments outside of +1s since most open source projects are done by developers in their free time outside of actual day jobs. it's quite possible that this change is come down the pipeline with other needed fixes.

**Comment by guyonroche** [comment]
Thanks @yanyiluo - yes, this is very much a free-time project for me :-)
As I can see this issue is a pain point for a lot of people, I'll give it my priority now.
Thanks for your patience...

**Comment by Nishchit14** [comment]
@guyonroche  we can understand.
And a big thanks for this awesome package :+1:  .

**Pull request merged**
