### PR TITLE
bugfix: numFmtHash's wrong hash-key makes too many <numFmt> tags for …

### PR DESCRIPTION
**Pull request by Youngbae-Jeon**
…the same format in styles.xml

### CODE REVIEW

**Comment by Youngbae-Jeon** [comment]
Too many number formats seems to makes the excel file unreadable.
https://support.microsoft.com/en-us/kb/213904

**Comment by keeneym** [comment]
I was having the same problem. This fix worked great.

FYI if it helps here was the specific error I was getting when validating sheets with too much style:

`Location of error: { 0}/x:worksheet[1]/x:sheetData[1]/x:row[4431]/x:c[11]
Error description: The attribute 's' has invalid value '66473'. The MaxInclusive constraint failed. The value must be less than or equal to 65490.`

So it looks like the max for xlsx is about 65490.

**Comment by surjikal** [comment]
This is fantastic, thanks!

**Comment by guyonroche** [comment]
I think this fix is already part of master, @Youngbae-Jeon - can you confirm?

**Comment by Youngbae-Jeon** [comment]
I have tested with the last commit on Aug 16, 2016 and found there are no more problems like this.
So I'm closing this pull request. Thank you.

**Pull request closed without merging**
