### PR TITLE
Minor fixes for stream handling

### PR DESCRIPTION
**Pull request by holm**
I upgraded from 0.2.38 to 0.2.46 today, and a few of our testcases failed. I tracked it down to two issues:

* The catch handler on the zip parsing was missing, and also wasn't propagating the error via the event emitter.
* The workbook writer was resolving the write when the zip-stream was done, not when the underlying stream was done. This meant that the write could resolve, while f.ex. a file was still being written to disk.

### CODE REVIEW

**Comment by neuralp** [comment]
Thank you for this simple fix.  I was just trying to figure out why my catch wasn't working while passing bad files to the readFile function and behold, you have the answer!

**Comment by guyonroche** [comment]
@holm - you wouldn't be able to add one of those failing test cases (or a smaller version of one) would you?
This (or something related to it) has been a recurring issue and it would be good to prevent it from happening again.

**Comment by holm** [comment]
I can try to find the time next week. I just needed it fixed quite urgently for one of our customers, but I should have time soon.

**Comment by guyonroche** [comment]
@holm - Just looking into this now, I hope to publish this weekend. I just noticed the change in zip-stream removed the .catch() on entry.async(), was that necessary or is it just that entry.async() doesn't reject?

**Comment by holm** [comment]
Yeah, that looks like a mistake. Should most likely emit the error there also.

**Comment by guyonroche** [comment]
@holm  Cool - thanks.
I've restored the other catch.
All tests passing with this and the updated lib versions so I've just published => 0.3.1.

**Comment by holm** [comment]
Thanks a lot for all your work on this library, it's pretty great!

**Pull request merged**
